/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShiftRouteImport } from './routes/shift'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FuelRouteImport } from './routes/fuel'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeesRouteImport } from './routes/fees'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShiftTripRouteImport } from './routes/shift.trip'
import { Route as ShiftSummaryRouteImport } from './routes/shift.summary'
import { Route as ShiftStartRouteImport } from './routes/shift.start'
import { Route as ShiftEndRouteImport } from './routes/shift.end'

const ShiftRoute = ShiftRouteImport.update({
  id: '/shift',
  path: '/shift',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FuelRoute = FuelRouteImport.update({
  id: '/fuel',
  path: '/fuel',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeesRoute = FeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftTripRoute = ShiftTripRouteImport.update({
  id: '/trip',
  path: '/trip',
  getParentRoute: () => ShiftRoute,
} as any)
const ShiftSummaryRoute = ShiftSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => ShiftRoute,
} as any)
const ShiftStartRoute = ShiftStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => ShiftRoute,
} as any)
const ShiftEndRoute = ShiftEndRouteImport.update({
  id: '/end',
  path: '/end',
  getParentRoute: () => ShiftRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fees': typeof FeesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/fuel': typeof FuelRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/setup': typeof SetupRoute
  '/shift': typeof ShiftRouteWithChildren
  '/shift/end': typeof ShiftEndRoute
  '/shift/start': typeof ShiftStartRoute
  '/shift/summary': typeof ShiftSummaryRoute
  '/shift/trip': typeof ShiftTripRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fees': typeof FeesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/fuel': typeof FuelRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/setup': typeof SetupRoute
  '/shift': typeof ShiftRouteWithChildren
  '/shift/end': typeof ShiftEndRoute
  '/shift/start': typeof ShiftStartRoute
  '/shift/summary': typeof ShiftSummaryRoute
  '/shift/trip': typeof ShiftTripRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fees': typeof FeesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/fuel': typeof FuelRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/setup': typeof SetupRoute
  '/shift': typeof ShiftRouteWithChildren
  '/shift/end': typeof ShiftEndRoute
  '/shift/start': typeof ShiftStartRoute
  '/shift/summary': typeof ShiftSummaryRoute
  '/shift/trip': typeof ShiftTripRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fees'
    | '/forgot-password'
    | '/fuel'
    | '/login'
    | '/profile'
    | '/setup'
    | '/shift'
    | '/shift/end'
    | '/shift/start'
    | '/shift/summary'
    | '/shift/trip'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fees'
    | '/forgot-password'
    | '/fuel'
    | '/login'
    | '/profile'
    | '/setup'
    | '/shift'
    | '/shift/end'
    | '/shift/start'
    | '/shift/summary'
    | '/shift/trip'
  id:
    | '__root__'
    | '/'
    | '/fees'
    | '/forgot-password'
    | '/fuel'
    | '/login'
    | '/profile'
    | '/setup'
    | '/shift'
    | '/shift/end'
    | '/shift/start'
    | '/shift/summary'
    | '/shift/trip'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeesRoute: typeof FeesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  FuelRoute: typeof FuelRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SetupRoute: typeof SetupRoute
  ShiftRoute: typeof ShiftRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shift': {
      id: '/shift'
      path: '/shift'
      fullPath: '/shift'
      preLoaderRoute: typeof ShiftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fuel': {
      id: '/fuel'
      path: '/fuel'
      fullPath: '/fuel'
      preLoaderRoute: typeof FuelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fees': {
      id: '/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof FeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shift/trip': {
      id: '/shift/trip'
      path: '/trip'
      fullPath: '/shift/trip'
      preLoaderRoute: typeof ShiftTripRouteImport
      parentRoute: typeof ShiftRoute
    }
    '/shift/summary': {
      id: '/shift/summary'
      path: '/summary'
      fullPath: '/shift/summary'
      preLoaderRoute: typeof ShiftSummaryRouteImport
      parentRoute: typeof ShiftRoute
    }
    '/shift/start': {
      id: '/shift/start'
      path: '/start'
      fullPath: '/shift/start'
      preLoaderRoute: typeof ShiftStartRouteImport
      parentRoute: typeof ShiftRoute
    }
    '/shift/end': {
      id: '/shift/end'
      path: '/end'
      fullPath: '/shift/end'
      preLoaderRoute: typeof ShiftEndRouteImport
      parentRoute: typeof ShiftRoute
    }
  }
}

interface ShiftRouteChildren {
  ShiftEndRoute: typeof ShiftEndRoute
  ShiftStartRoute: typeof ShiftStartRoute
  ShiftSummaryRoute: typeof ShiftSummaryRoute
  ShiftTripRoute: typeof ShiftTripRoute
}

const ShiftRouteChildren: ShiftRouteChildren = {
  ShiftEndRoute: ShiftEndRoute,
  ShiftStartRoute: ShiftStartRoute,
  ShiftSummaryRoute: ShiftSummaryRoute,
  ShiftTripRoute: ShiftTripRoute,
}

const ShiftRouteWithChildren = ShiftRoute._addFileChildren(ShiftRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeesRoute: FeesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  FuelRoute: FuelRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SetupRoute: SetupRoute,
  ShiftRoute: ShiftRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
