/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FuelRouteImport } from './routes/fuel'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeesRouteImport } from './routes/fees'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShiftIndexRouteImport } from './routes/shift.index'
import { Route as ShiftTripRouteImport } from './routes/shift.trip'
import { Route as ShiftSummaryRouteImport } from './routes/shift.summary'
import { Route as ShiftStartRouteImport } from './routes/shift.start'
import { Route as ShiftEndRouteImport } from './routes/shift.end'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRecordsRouteImport } from './routes/admin.records'
import { Route as AdminFeesRouteImport } from './routes/admin.fees'
import { Route as AdminExportRouteImport } from './routes/admin.export'
import { Route as AdminDriversRouteImport } from './routes/admin.drivers'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FuelRoute = FuelRouteImport.update({
  id: '/fuel',
  path: '/fuel',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeesRoute = FeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftIndexRoute = ShiftIndexRouteImport.update({
  id: '/shift/',
  path: '/shift/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftTripRoute = ShiftTripRouteImport.update({
  id: '/trip',
  path: '/trip',
  getParentRoute: () => ShiftRoute,
} as any)
const ShiftSummaryRoute = ShiftSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => ShiftRoute,
} as any)
const ShiftStartRoute = ShiftStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => ShiftRoute,
} as any)
const ShiftEndRoute = ShiftEndRouteImport.update({
  id: '/end',
  path: '/end',
  getParentRoute: () => ShiftRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecordsRoute = AdminRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeesRoute = AdminFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExportRoute = AdminExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDriversRoute = AdminDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/fees': typeof FeesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/fuel': typeof FuelRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/setup': typeof SetupRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/records': typeof AdminRecordsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/shift/end': typeof ShiftEndRoute
  '/shift/start': typeof ShiftStartRoute
  '/shift/summary': typeof ShiftSummaryRoute
  '/shift/trip': typeof ShiftTripRoute
  '/shift/': typeof ShiftIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/fees': typeof FeesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/fuel': typeof FuelRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/setup': typeof SetupRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/records': typeof AdminRecordsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/shift/end': typeof ShiftEndRoute
  '/shift/start': typeof ShiftStartRoute
  '/shift/summary': typeof ShiftSummaryRoute
  '/shift/trip': typeof ShiftTripRoute
  '/shift': typeof ShiftIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/fees': typeof FeesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/fuel': typeof FuelRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/setup': typeof SetupRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/export': typeof AdminExportRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/records': typeof AdminRecordsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/shift/end': typeof ShiftEndRoute
  '/shift/start': typeof ShiftStartRoute
  '/shift/summary': typeof ShiftSummaryRoute
  '/shift/trip': typeof ShiftTripRoute
  '/shift/': typeof ShiftIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/fees'
    | '/forgot-password'
    | '/fuel'
    | '/login'
    | '/profile'
    | '/setup'
    | '/admin/dashboard'
    | '/admin/drivers'
    | '/admin/export'
    | '/admin/fees'
    | '/admin/records'
    | '/admin/settings'
    | '/shift/end'
    | '/shift/start'
    | '/shift/summary'
    | '/shift/trip'
    | '/shift/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/fees'
    | '/forgot-password'
    | '/fuel'
    | '/login'
    | '/profile'
    | '/setup'
    | '/admin/dashboard'
    | '/admin/drivers'
    | '/admin/export'
    | '/admin/fees'
    | '/admin/records'
    | '/admin/settings'
    | '/shift/end'
    | '/shift/start'
    | '/shift/summary'
    | '/shift/trip'
    | '/shift'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/fees'
    | '/forgot-password'
    | '/fuel'
    | '/login'
    | '/profile'
    | '/setup'
    | '/admin/dashboard'
    | '/admin/drivers'
    | '/admin/export'
    | '/admin/fees'
    | '/admin/records'
    | '/admin/settings'
    | '/shift/end'
    | '/shift/start'
    | '/shift/summary'
    | '/shift/trip'
    | '/shift/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  FeesRoute: typeof FeesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  FuelRoute: typeof FuelRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SetupRoute: typeof SetupRoute
  ShiftIndexRoute: typeof ShiftIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fuel': {
      id: '/fuel'
      path: '/fuel'
      fullPath: '/fuel'
      preLoaderRoute: typeof FuelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fees': {
      id: '/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof FeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shift/': {
      id: '/shift/'
      path: '/shift'
      fullPath: '/shift/'
      preLoaderRoute: typeof ShiftIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shift/trip': {
      id: '/shift/trip'
      path: '/trip'
      fullPath: '/shift/trip'
      preLoaderRoute: typeof ShiftTripRouteImport
      parentRoute: typeof ShiftRoute
    }
    '/shift/summary': {
      id: '/shift/summary'
      path: '/summary'
      fullPath: '/shift/summary'
      preLoaderRoute: typeof ShiftSummaryRouteImport
      parentRoute: typeof ShiftRoute
    }
    '/shift/start': {
      id: '/shift/start'
      path: '/start'
      fullPath: '/shift/start'
      preLoaderRoute: typeof ShiftStartRouteImport
      parentRoute: typeof ShiftRoute
    }
    '/shift/end': {
      id: '/shift/end'
      path: '/end'
      fullPath: '/shift/end'
      preLoaderRoute: typeof ShiftEndRouteImport
      parentRoute: typeof ShiftRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/records': {
      id: '/admin/records'
      path: '/records'
      fullPath: '/admin/records'
      preLoaderRoute: typeof AdminRecordsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fees': {
      id: '/admin/fees'
      path: '/fees'
      fullPath: '/admin/fees'
      preLoaderRoute: typeof AdminFeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/export': {
      id: '/admin/export'
      path: '/export'
      fullPath: '/admin/export'
      preLoaderRoute: typeof AdminExportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/drivers': {
      id: '/admin/drivers'
      path: '/drivers'
      fullPath: '/admin/drivers'
      preLoaderRoute: typeof AdminDriversRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDriversRoute: typeof AdminDriversRoute
  AdminExportRoute: typeof AdminExportRoute
  AdminFeesRoute: typeof AdminFeesRoute
  AdminRecordsRoute: typeof AdminRecordsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDriversRoute: AdminDriversRoute,
  AdminExportRoute: AdminExportRoute,
  AdminFeesRoute: AdminFeesRoute,
  AdminRecordsRoute: AdminRecordsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  FeesRoute: FeesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  FuelRoute: FuelRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SetupRoute: SetupRoute,
  ShiftIndexRoute: ShiftIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
